\documentclass[a4paper,11pt,leqno]{report}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

\usepackage{amsmath, amssymb, mdframed, caption, subcaption, graphicx, enumitem}
\usepackage{nicefrac}

\usepackage{hyperref}
\hypersetup{colorlinks=true, urlcolor=blue, breaklinks=true}

\newmdtheoremenv{Definition}{Definition}[chapter]
\newmdtheoremenv{Exercise}[Definition]{Exercise}
\newmdtheoremenv{Theorem}[Definition]{Theorem}
\newmdtheoremenv{Lemma}[Definition]{Lemma}

\newcommand{\supp}{\operatorname{supp}} 
\newcommand{\E}{\mathbb{E}}
\newcommand{\eps}{\varepsilon}

\newcommand{\philip}[1]{ \textcolor{red}{\textbf{Philip:} #1}}
\newcommand{\chris}[1]{ \textcolor{blue}{\textbf{Chris:} #1}}

\title{Basic Probability}
\date{}



\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\setcounter{chapter}{5}

\chapter{The EM algorithm and Information Theory}

\section{Mixture Models}\label{sec:mixtureModels}

In the previous chapter we have mentioned that it may happen that a likelihood function has multiple 
maxima and that sometimes it may be hard or impossible to find the global maximum (i.e.\ the maximum
with the overall highest likelihood value). Such a situation occurs whenever the probabilistic model
that we use to model our observations is a \textbf{latent} or \textbf{hidden variable model}. Latent variable
models are models that besides modelling observed data also model a portion of unobserved data. For
example, if we look at the income distribution of a population we may want to further differentiate
between age groups. If the age of all or some members of the population is not provided in the data, we
can still model it as a latent variable. The difficulty is that we will have to make inferences about the
age of an individual based on other information that we have about it (e.g. the income). 

While it may in general be quite hard to formulate latent variable models, there are certain standard
latent variable models that have wide-spread applications. One such class are \textbf{mixture models}.

\begin{Definition}[Mixture Model]\label{def:mixtureModel}
We assume jointly distributed random variables $ X=X_{1}^{n} $ and $ Y=Y_{1}^{n} $ where $ Y $ is categorical and
$ \mathcal{Y} = \{c_{1}, \ldots, c_{k}\} $. The $ X_{i} $ are observed data, the $ Y_{i} $ are latent
or observed and the $ c_{j}, 1\leq j \leq k $ are called mixture components. 
If the distribution
$ P(X_{1}^{n}=x_{1}^{n}, Y_{1}^{n} = y_{1}^{n}) $ factors as
$$ P(X_{1}^{n}=x_{1}^{n}, Y_{1}^{n} = Y_{1}^{n})= P(Y_{1}^{n} = y_{1}^{n}) \prod_{i=1}^{n} P(X_{i}=x_{i}|Y_{i} = y_{i}) \ . $$
we call this model a mixture model. The marginal probabilities $ P(Y_{i}=y_{i}) $ for $ 1 \leq i \leq n $ are called
mixture weights.
\end{Definition}

Mixture models are extremely useful whenever we have different ways to think about our data. Each way
of conceptualising our data can be encoded by one of the mixture components of the mixture model. The modelling
of the data under that view is done by the conditional distribution induced by the mixture component.
This can help us to build a better overall model of our data. Let us introduce a running example that
we use for the rest of this section. 

\paragraph{Example of a mixture model} Assume we observe 20 sequences of coin tosses. Each sequence
contains 10 flips. We also know that there are 3 coins with which these sequences could possibly have been
generated and for each sequence a different coin may have been used. We want to find out what the biases
of the coins are (i.e. the parameters of the binomial distributions associated with the coins) and the probability
for each coin to have generated a particular sequence.
 
We could assume that the entire data set was generated by exactly one coin. We would then employ maximum likelihood estimation 
to find the parameter of that coin. However, this model might actually turn out to be
pretty bad because we are committing to picking one coin only. This is a bad assumption. Recall that we said in the beginning that
each sequence may possibly have been generated by a different coin. 

A mixture model comes to the rescue. Instead of assuming that only one coin has generated all 20 sequences,
we assume that all three coins have contributed to generating the 20 sequences. However, their contributions
may not be equal. This inequality is exactly what the mixture weights capture. 

In order to model the contribution of each coin, we introduce at latent RV $ Y $ over mixture components with values $ c_{1}, c_{2}, c_{3} $ representing the three coins.
In the present case, each mixture component is linked to a binomial distribution, parametrized by the biases of
the coins. We will also adopt the often-used assumption
that the mixture components are independent of each other given their mixture components. This means that the coin that generated each
sequence of coin flips was chosen independently of the coins used for the other sequences. As usual, we call our data $ x $. 
This information suffices to formulate our mixture model.
\begin{align} 
&P(X=x_{1}^{n}|Y_{1}^{n}=Y_{1}^{n},\Theta=\theta) \label{eq:mixtureExample} \\
&= \prod_{i=1}^{n} P(Y_{i}= y_{i}|\Theta=\theta)P(X_{i}=x_{i}|Y_{i}=y_{i},\Theta=\theta) \nonumber 
\end{align}

Notice that if we were given the mixture weights, estimating
the parameters of the mixture components would be easy: we would simply find the MLE for each mixture component separately. The mixture
model could then easily be constructed because the mixture weights are known. 

Usually, we face a more difficult problem when working with mixture models. Neither the mixture
weights nor the parameters of the mixture components are known. In this case, doing straighforward MLE is impossible because the data are
incomplete\footnote{In general, whenever you have complete data, analytic MLE computation is possible. The moment your data is incomplete, it becomes impossible.}. 

How can we go about estimating the model parameters, i.e. the parameters of the mixture components and the mixture weights?
Each factor
in \eqref{eq:mixtureExample} is in fact a joint distribution (by the chain rule). We exploit this to rewrite the model as a model of the
observed data only.
\begin{align}\label{eq:marginal}
P(X=x_{1}^{n}| \Theta= \theta) &= \prod_{i=1}^{n} \sum_{j=1}^{3} P(X_{i}=x_{1},Y_{i}=c_{j}| \Theta= \theta)
\end{align}
where the sums are simple marginalisation steps. Now that we have related mixture models to the probability of the observed data, we can hope to estimate
their parameters using the maximum likelihood principle.

There is one remaining problem, however: if the mixture weights are unknown, there is no closed-form solution for estimating the likelihood function. This is because
the likelihood depends on the parameters of the mixture components whose distribution, given
by the mixture weights, is unknown. This means that while we can compute the likelihood for each
individual mixture component, we cannot compute the likelihood of the entire mixture model because we
do not know how much each component contributes to the overall likelihood term. As a consequence, we can not 
simply apply calculus as we have been doing up to now. For this reason, we turn to the \textbf{EM algorithm}, 
that allows to at least find a local maximum of the likelihood function.

One final note: At the beginning we introduced latent variable models (and hence mixture models) as models
of \textit{latent data}. We have cast the problem of inferring the mixture weights as inferring a 
distribution over mixture components, however. One may argue that those are not data, neither latent nor 
observed. This is a fair criticism but there is an easy way out. Simply imagine that each sequence of coin
flips was annotated with a pointer to the mixture component (the coin) that generated it. This annotation
is clearly part of the data. Since in our actual data, these annotations are missing, we treat them as 
latent data.

\section{The EM Algorithm}

In order to estimate the parameters of mixture models, we can employ a classical algorithm of 
\textbf{unsupervised learning}\footnote{Whenever the feature of our data that we want to predict, such a the coin which generated a sequence,
is observed, we speak of supervised learning. If the target feature is latent, we speak of unsupervised learning.}, 
namely the \textbf{expectation-maximisation (EM) algorithm}. This
algorithm allows to find a local maximum of the likelihood function of mixture models or, more
generally, models with missing data. 

\paragraph{Another example of latent data} To give you some more intuition for what latent data is we provide a further example that has
spawned a lot of research. Assume you run a website that recommends movies
based on a user's preferences. In order to make statistical predictions about what type of user
likes what kind of movie, you ask your users to rate movies according to different categories.
Say you ask your users to rate the movies for entertainment value, action and fun. What may happen is
that some of your users only rate a movie in one or two of these three categories. However, these
ratings are still valuable to you and you do not want to throw them away, just because the rating is
incomplete. Thus you have a data set with some missing data that you have to fill in somehow.
\bigskip

In mixture models, annotations that tell you which mixture component
generated a given data point can be thought of as missing data. As we have seen, such annotations
are usually missing and thus we cannot do maximum likelihood estimation. The idea of EM is to
make an educated guess at the probability with which each mixture component could \textit{potentially}
have generated a data point $ x_{i} $. What we do know is our observed data and some initial guess of the mixture
weights which act as prior probabilities for the mixture components (this guess may be arbitrary). 
Our educated guess is then simply based on Bayes' rule. It is the posterior probability of each mixture
component given the data point $ x_{i} $.

Using the posterior over the latent (missing) data, the EM algorithm allows us to probabilistically fill in the missing data and find good mixture weights
(where you should understand \textit{good} in the maximum-likelihood sense). The idea behind the
algorithm is simple: first, compute the expected number of occurrences of the missing data values (the mixture 
components). Then treat these expectations as observed and do maximum likelihood estimation as usual\footnote{Notice that expectations can be
fractional and thus when treating them as observations we are handling a dataset with fractional observations. While this may be conceptually awkward
it does not change the mathematics of maximum likelihood estimation.}. Repeat the procedure 
until the likelihood does not increase any further. Notice that this procedure requires to
fix the number of mixture components in advance.

More formally, assume a data set $ X=x $. Furthermore, define $ Y $ as a random variable over latent data that can
take on $ |Y| $ possible values. Then the likelihood function is 
\begin{align}
L_{x}(\theta) = P(X=x|\Theta=\theta) = \underset{j=1}{\overset{|Y|}{\sum}} P(X=x, Y=y_{j}|\Theta=\theta)
\end{align}
where $ \Theta $ ranges over the parameters of the joint distributiforon $ P_{XY} $. Recall that EM
probabilistically fills in missing data. However, since we are doing maximum likelihood estimation, we
are not so much interested in the missing data itself but rather in the sufficient statistics of
that data (see Section \ref{sec:sufficientStats}). Since we cannot directly obtain the sufficient statistics
of missing data, we will instead compute the \textit{expected sufficient statistics}\footnote{
Because we are referring to sufficient statistics our exposition of EM is specific to distributions
in the exponential family. The EM algorithm can also be made more general. However, since virtually
all distributions that are of interest in practice do belong to the exponential family, we will not make this kind of generalisation.
}.

The EM algorithm is an iterative 
algorithm, meaning we repeat its steps several
times. We use superscripts to indicate the number $l$ of the repetition, where $ 0 \leq l \leq k $.
To formalize the EM algorithm, assume we are at iteration $l$ for which we have some parameter estimate 
$\theta^{(l)} $ (the initial estimate $\theta^{(0)}$ can be set arbitrarily). Based on this parameter 
estimate we then compute the expected sufficient statistics of our model which we will call $ t(y,x) $.
\begin{equation} \label{Estep}
t(y,x)^{(l+1)} = \E(t(Y,x)|X = x,\Theta = \theta^{(l)})
\end{equation} 

Equation~\eqref{Estep} is known as the \textbf{E(xpectation)-step} of the EM algorithm. This name
comes from the fact that in this step we compute the expected sufficient statistics. 
To make the algorithm complete, we still miss a
\textbf{M(aximization)-step}. But that step is simple. We pretend that the expected sufficient statistics of 
the latent data were actually observed. Once we pretend to observe the expected statistics, the maximization 
step can be performed using be maximum-likelihood estimation:
\begin{equation} \label{Mstep}
\theta^{(l+1)} = \underset{\theta}{\arg\max} P(X=x, t(Y,X) = t(y,x)^{(l+1)}|\theta)
\end{equation}

\begin{Definition}[EM algorithm]\label{def:EM}
We assume a data set $ x $ and postulate that there is unobserved data $ y $. We also
assume a probabilistic model $ P(X=x,Y=y|\Theta = \theta) $ whose parameters are realisations of a RV
$ \Theta $. Let $ t(x,y) $ be the sufficient statistics for that model. Then any
iterative algorithm with $ m $ iterations that performs the following
steps for $0\leq i \leq m-1$, 
\begin{align*}
\mbox{\textbf{E-step:} } \quad t(y,x)^{(l+1)} &= \E(t(Y,x) \mid X = x, \Theta = \theta^{(i)}) \\
\mbox{\textbf{M-step:} } \qquad \theta^{(l+1)} &= \underset{\theta}{\arg\max} \; P(X=x, t(Y,x) = t(Y,x)^{(i+1)} \mid \Theta = \theta) 
\end{align*}
to update the model parameters is called an EM algorithm. 
\end{Definition}

\section{Example of an EM Algorithm for a Mixture Model}

Assume as in Section~\ref{sec:mixtureModels} that our data is $ x=x^{20}_{1} $ where each $ x_{i} $ is the 
number of heads that we observed in a sequence of a 10 coin tosses. Again we also assume mixture components representing three coins which are linked
to binomials with parameters representing the biases of the coins. 
The latent data in this case is an annotation that for each observed sequence $ x_{i} $ reveals the coin that has been used
to generate that sequence. Thus we have latent data $ y=y_{1}^{n} $ where each $ y_{i} $ can be one of the three mixture components. 
We make the additional assumption that choosing a coin to generate a particular sequence is done independently of the coins chosen
to generate all the other sequences. This has the effect that in our model the latent data points will be independent\footnote{The assumption
that the mixture components in a mixture model are independent is actually quite common.}.

\paragraph{E-step} Initially we arbitrarily assume that the coins have biases of $ 0.4, 0.5 $ and $ 0.65 $, meaning that we initialize the binomial parameters of the data-generating
distributions as follows:
\begin{equation}
\theta^{(0)}_{c_{1}} = 0.4 \hskip 0.5cm  \theta^{(0)}_{c_{2}} = 0.5 \hskip 0.5cm  \theta^{(0)}_{c_{3}} = 0.65
\end{equation}
We also assume that the fair coin is more likely to be used and hence set its initial mixture weight to $ 0.5 $ and the mixture weights of the 
other two coins to $ 0.25 $ (any other choice would also be fine). Let 
us take a closer look at our data. To shorten notation, we write it as a list where the i$ ^{th} $ entry is the value of $ x_{i} $.
$$ [6, 5, 4, 2, 2, 6, 5, 5, 4, 2, 5, 2, 4, 4, 6, 4, 5, 6, 3, 3 ] $$ 
Then for each $ x_{i} $ we check how likely each coin is to have generated that point. In order to compute the posterior for each coin given a data point, we need
the likelihood for that data point. For the first observation we get the following likelihood values.
\begin{align}
&P(X_{1}=6|Y_{1} = c_{1}) = P(X_{1}=6|Y_{1}=c_{1},\Theta = 0.4) = 0.1114767& \\
&P(X_{1}=6|Y_{1} = c_{2}) = P(X_{1}=6|Y_{2}=c_{2},\Theta = 0.5) = 0.2050781& \nonumber \\ 
&P(X_{1}=6|Y_{1} = c_{3}) = P(X_{1}=6|Y_{3}=c_{3},\Theta = 0.65) = 0.2376685& \nonumber
\end{align}

Recall that the mixture weights are nothing else than priors over mixture components. Hence, in order to get the joint distribution over observed and
latent data, we multiply the likelihoods by the mixture weights.
\begin{align}
&P(X_{1}=6,Y_{1} = c_{1}) = 0.25 \times P(X_{1}=6|Y_{1}=c_{1},\Theta = 0.4) = 0.02786918 \\
&P(X_{1}=6,Y_{1} = c_{2}) = 0.5 \times P(X_{1}=6|Y_{2}=c_{2},\Theta= 0.5)  = 0.1025391 \nonumber \\ 
&P(X_{1}=6,Y_{1} = c_{3}) =  0.25 \times P(X_{1}=6|Y_{3}=c_{3},\Theta = 0.65)  = 0.05941712 \nonumber
\end{align}

We are ultimately interested in the posterior over mixture components. Because we are dealing with a categorical
distribution here, the posterior probability is exactly the expected
number of times that each coin has generated data point $ x_{1} $. This is to say that
$\E[Y=c_{j}|X_{1}=6, \Theta = \theta^{0}] = P(Y_{1}=c_{j}|X_{1}=6, \Theta=\theta^{0}) $. The
posterior given $ x_{1} $ is shown below.
\begin{align}\label{eq:posterior}
P(Y_{1} = c_{1}|X_{1}=6,\Theta= \theta^{0}) = \frac{P(X_{1}=6,Y_{1} = c_{1}|\Theta= \theta^{0})}{P(X_1 = 6|\Theta= \theta^{0})} = 0.146814 \\
P(Y_{1} = c_{2}|X_{1}=6,\Theta= \theta^{0}) = \frac{P(X_{1}=6,Y_{1} = c_{2}|\Theta= \theta^{0})}{P(X_1 = 6|\Theta= \theta^{0})} = 0.5401758 \nonumber \\
P(Y_{1} = c_{3}|X_{1}=6,\Theta= \theta^{0}) = \frac{P(X_{1}=6,Y_{1} = c_{3}|\Theta= \theta^{0})}{P(X_1 = 6|\Theta= \theta^{0})} = 0.3130094 \nonumber
\end{align}

We compute these expectations over mixture components for each data point and add them up. The reason we can simply add the expectation is that
the latent variables are independent and consequently their expectations are independent. If this was not the case, simple adding would not
be possible. How exactly the expectations can be accumulated depends on how the model's distribution over latent variables factorises. This has to
be handled on a case-by-case basis. For our examples the expectations for each outcome can be found in Table~\ref{tab:posteriors}.

One the expectations have been added, we need to compute the sufficient statistics for our model. First of all notice that we are dealing with
a mixture model where the latent variables are always categorical. Thus, in order to update the parameters of $ P_{Y} $ we need to find the
sufficient statistics for a categorical distribution. Recall that these sufficient statistics are simply the counts per outcome observed in
the data. Thus the expected sufficient statistics for a categorical are the expected counts per outcome. But these are simply the posterior
probabilities! Thus we simply need to multiply the posteriors per of each observed outcome with the number of times this outcome was
seen in the data and sum the over all observed outcomes. For mixture component $ c_{1} $ (the first coin with parameter $ \theta^{0}_{c_{1}} = 0.4 $) this gives
\begin{align}
\E(Y = c_{1}|X=x,\Theta= \theta^{0}) = 2 \times 0.5674795 + 3 \times 0.4568744 \\ 
+ 4 \times 0.3436451 + 5 \times 0.237068 + 6 \times 0.1114767 = 5.946387 \nonumber \ .
\end{align}
By parallel calculations we get $ \E(Y = c_{2}X=x,\Theta= \theta^{0}) = 10.7153 $ and $ \E(Y = c_{3}X=x,\Theta= \theta^{0}) = 3.338238 $. 
These are our expected sufficient statistics. Importantly, we get 
$ \E[Y = c_{1}|X=x,\Theta= \theta^{0}] + \E[Y = c_{2}|X=x,\Theta= \theta^{0}] + \E[Y = c_{3}|X=x,\Theta= \theta^{0}] \approx 20 $ (there is some slight numerical imprecision
caused by our computer). Notice that this is a useful debugging technique when implementing the algorithm: if the expected number of mixture components
does not add up to the number of latent variables in your model, then you almost certainly have a bug in your code!

\begin{table}
\center

\begin{tabular}{c|c|c|c|c}
\hline
outcome & \#occurrences & 0.4 & 0.5 & 0.65\\
\hline
2 & 4 & 0.5674795 & 0.4124300 & 0.0200905\\
\hline
3 & 2 & 0.4568744 & 0.4980674 & 0.0450583\\
\hline
4 & 5 & 0.3436451 & 0.5619435 & 0.0944114\\
\hline
5 & 5 & 0.2370680 & 0.5814960 & 0.1814361\\
\hline
6 & 4 & 0.1468149 & 0.5401758 & 0.3130094\\
\hline
\end{tabular}


\caption{Posteriors for the mixture components of the coin flip data set from our EM example. The mixture components are 
represented by the parameters of the distributions that they are linked to.}
\label{tab:posteriors}
\end{table}

Next we turn to the sufficient statistics for the binomial distributions linked to the mixture components. These are the counts of the observed outcomes. However,
since the binomials are conditional distributions (they are conditioned on the identity of the coins), the counts have to be taken with respect to their conditioning
contexts. In other words: we cannot count the observed outcomes independently but we have to count pairs of observed and latent variables. Formally this means that 
for one binomially distributed observation $ x_{i} $ that $ E[X=x_{i},Y_{i}=c_{j}|\Theta=\theta^{0}] = P(Y_{i}=c_{j}|X_{i}=x_{i}, \Theta=\theta^{0}) $. This is again
just the posterior that we find in Table~\ref{tab:posteriors}. The only difference is how we are going to sum the posteriors this time. Before we were interested
in the sufficient statistics of the categorical over mixture components and thus summed over all observed outcomes. Now we actually need to discriminate between
observed outcomes. We only sum over observations that had the same outcome. Working with Table~\ref{tab:posteriors} this means that we simply multiplying each
cell, which contains the posterior for one observation, by the number of times each outcome has been observed in the data set. For the pairs $ (X=2,Y=c_{1}) $
and $ (X=4,Y = c_{3}) $ this gives:
\begin{align}
E[X=2,Y=c_{1}|\Theta=\theta^{0}_{c^{1}}] = 4 \times 0.5674795 = 2.269918 \\
E[X=4,Y=c_{3}|\Theta=\theta^{0}_{c^{3}}] = 5 \times 0.0944114 = 0.472057
\end{align} 
The expected sufficient statistics for all binomials can be found in Table~\ref{tab:binomPosteriors}. That we have computed all sufficient statistics
for our model means that we have completed the E-step!

\begin{table}
\center

\begin{tabular}{c|c|c|c}
\hline
outcome & 0.4 & 0.5 & 0.65\\
\hline
2 & 2.2699180 & 1.6497199 & 0.0803621\\
\hline
3 & 0.9137487 & 0.9961348 & 0.0901165\\
\hline
4 & 1.7182254 & 2.8097177 & 0.4720569\\
\hline
5 & 1.1853398 & 2.9074798 & 0.9071804\\
\hline
6 & 0.5872594 & 2.1607030 & 1.2520376\\
\hline
\end{tabular}


\caption{Posteriors expectations of the observed outcomes in the context of each mixture component.}
\label{tab:binomPosteriors}
\end{table}



\paragraph{M-step} As pointed out before, the M-step is rather trivial once we have all the necessary expectations. Recall that according to our model, 
the mixture components are categorically
distributed and thus in the M-step we want to find the MLE of that categorical. In general, the MLE for $ \theta_{j} $ of a categorical is
$ \frac{\#c_{j}}{n} $\footnote{This fact can easily be seen by letting $ \#c_{j} $ be the number of successes in the realisation of a binomial RV and the sum of all
$ \#c_{m},~m \not = j $ be the number of failures. Then clearly $ \frac{\#c_{j}}{n} $ is the MLE.}. In our case $ n=20 $. Since we have not observed the
latent variables, we simply use their expected sufficient statistics (their expected counts) instead. Thus we set 
$ \theta_{j}^{(1)} = \frac{\E[Y = c_{j}|X=x,\Theta= \theta^{0}]}{20} $. The updated mixture weights then are 
\begin{align}
P(Y=c_{1}|\Theta= \theta^{1}) = 0.3337246 \\
P(Y=c_{2}|\Theta= \theta^{1}) = 0.5261878 \nonumber \\
P(Y=c_{3}|\Theta= \theta^{1}) = 0.1400877 \nonumber
\end{align}

We already know the maximum likelihood estimate for binomial distributions from 
Section\ref{sec:parameterEstimation}. The only novelty when it comes to EM for mixture models
is that the conditioning contexts are not observed anymore. Again, we fall back on the expected
context counts again. The the maximum likelihood estimate for an outcome $ x $ conditioned on
mixture component $ c_{j} $ is
$$ \theta_{c_{j}x}^{1} = \frac{E[X=x|Y=c_{j},\Theta=\theta^{0}]}{\sum_{x \in \mathcal{X}}E[X=x|Y_{i}=c_{j},\Theta=\theta^{0}]}\ . $$
The updated binomial distributions are given in Table~\ref{tab:newBinoms}. This completes our parameter
updates and thus the M-step. We can start the next round of estimation by doing the E-step using the
updated parameters $ \theta^{1} $. We will stop iterating when the parameters do not change anymore or
after a pre-specified number of iterations.

\begin{table}
\center
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\begin{tabular}{c|c|c|c}
\hline
outcome & 0.4 & 0.5 & 0.65\\
\hline
2 & 0.3400885 & 0.1567615 & 0.0286828\\
\hline
3 & 0.1369016 & 0.0946558 & 0.0321643\\
\hline
4 & 0.2574317 & 0.2669881 & 0.1684862\\
\hline
5 & 0.1775925 & 0.2762778 & 0.3237902\\
\hline
6 & 0.0879856 & 0.2053167 & 0.4468764\\
\hline
\end{tabular}


\end{knitrout}
\caption{}
\label{tab:newBinoms}
\end{table}

%\begin{table}
%\center
%\begin{tabular}{|c|c|c|c|c|}
%\hline
%Outcome & \# occurrences	& $ \theta_{1}~(0.4) $ 	& $ \theta_{2}~(0.5) $ 	& $ \theta_{4}~(0.65) $ \\
%\hline
%2		& 2				& 0.5674795				& 0.41243				& 0.02009052				\\
%3		& 3				& 0.4568744				& 0.4980674				& 0.04505826				\\
%4		& 4				& 0.3436451				& 0.5619435				& 0.09441138				\\
%5		& 5				& 0.237068				& 0.581496				& 0.1814361				\\
%6		& 6				& 0.146814				& 0.5401758				& 0.3130094				\\
%\hline
%\end{tabular}
%\caption{Posteriors for the mixture components of the coin flip data set from our EM example. The mixture components
%}
%\label{tab:posteriors}
%\end{table}

%%% Local Variables:
%%% mode: latex
%%% TeX-master: "chapter6"
%%% End:

\end{document}
